# Generated by Django 4.2.16 on 2024-12-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_system', models.CharField(max_length=255)),
                ('delta_winner', models.IntegerField()),
                ('delta_loser', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='competitors.competitor')),
                ('winner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='competitors.competitor')),
            ],
        ),
    ]
