# Generated by Django 4.2.16 on 2024-12-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchups', '0002_alter_matchup_loser_id_alter_matchup_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups', to=settings.AUTH_USER_MODEL),
        ),
    ]
