# Generated by Django 4.2.16 on 2024-12-15 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_alter_competitordetails_competitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchups', '0004_matchup_delta_loser_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_first_competitor', to='competitors.competitor')),
                ('competitor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_second_competitor', to='competitors.competitor')),
                ('profile_id', models.OneToOneField(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_matchup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
