# Generated by Django 4.2.16 on 2024-12-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_roundcompetitor_delta_tournament_and_more'),
        ('matchups', '0006_savedmatchup_competitor_1_ii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='tournament_matchup_id',
            field=models.ForeignKey(blank=True, db_column='tournament_matchup_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournaments.tournamentmatchup'),
        ),
    ]
