# Generated by Django 4.2.16 on 2024-12-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='competitor_id',
            field=models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='competitors.competitor'),
        ),
    ]
