# Generated by Django 4.2.16 on 2024-12-15 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitors', '0002_alter_competitordetails_competitor'),
        ('ratings', '0002_alter_rating_competitor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('matchups', models.IntegerField(default=0)),
                ('tournaments', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_id', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='profiles_ratings', to='competitors.competitor')),
                ('profile_id', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
