# Generated by Django 4.2.16 on 2024-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0003_matchup_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='delta_loser_profile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='delta_winner_profile',
            field=models.IntegerField(null=True),
        ),
    ]
