# Generated by Django 4.2.16 on 2024-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0005_savedmatchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmatchup',
            name='competitor_1_ii',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedmatchup',
            name='competitor_2_ii',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
