# Generated by Django 4.2.16 on 2024-12-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbase',
            name='template_tournament_id',
            field=models.ForeignKey(blank=True, db_column='template_tournament_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.templatetournament'),
        ),
    ]
