# Generated by Django 4.2.16 on 2024-12-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_roundcompetitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='winner_id',
            field=models.ForeignKey(blank=True, db_column='winner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchup_winner', to='tournaments.roundcompetitor'),
        ),
    ]
