# Generated by Django 4.2.16 on 2024-12-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentmatchup_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchup',
            name='matchup_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
