# Generated by Django 4.2.16 on 2024-12-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentmatchup_matchup_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatchup',
            name='matchup_number',
        ),
    ]
