# Generated by Django 4.2.16 on 2024-12-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_tournamentmatchup_matchup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchup',
            name='matchup_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
