# Generated by Django 4.2.16 on 2024-12-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamentmatchup_matchup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='matchup_number',
            field=models.PositiveIntegerField(),
        ),
    ]
