# Generated by Django 4.2.16 on 2024-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_alter_tournamentbase_competitors_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundcompetitor',
            name='delta_tournament',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentcompetitor',
            name='delta_tournament',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='rating_system_name',
            field=models.CharField(default='elo_32', max_length=255),
        ),
    ]
