# Generated by Django 4.2.16 on 2024-12-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_tournamentround_rating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundcompetitor',
            name='delta_tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentcompetitor',
            name='delta_tournament',
        ),
    ]
