# Generated by Django 4.2.16 on 2024-12-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_roundcompetitor_delta_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='tournament_round_id',
            field=models.ForeignKey(db_column='tournament_round_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_matchups', to='tournaments.tournamentround'),
        ),
    ]
