# Generated by Django 4.2.16 on 2024-12-22 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_alter_tournamentmatchup_tournament_round_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundcompetitor',
            name='tournament_round_id',
            field=models.ForeignKey(db_column='tournament_round_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_competitors', to='tournaments.tournamentround'),
        ),
        migrations.AlterField(
            model_name='tournamentcompetitor',
            name='tournament_base_id',
            field=models.ForeignKey(db_column='tournament_base_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors', to='tournaments.tournamentbase'),
        ),
    ]
