# Generated by Django 4.2.16 on 2024-12-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_alter_roundcompetitor_tournament_round_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcompetitor',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('eliminated', 'eliminated'), ('winner', 'winner')], default='active', max_length=255),
        ),
    ]
