# Generated by Django 4.2.16 on 2024-12-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_alter_tournamentcompetitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetournament',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('archived', 'archived')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentbase',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('completed', 'completed'), ('archived', 'archived')], default='not started', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournamentcompetitor',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('active', 'active'), ('eliminated', 'eliminated'), ('winner', 'winner')], default='not started', max_length=255),
        ),
    ]
