# Generated by Django 4.2.16 on 2024-12-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_rename_competitors_number_templatetournament_competitors_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentround',
            name='competitors_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='matchups_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
