# Generated by Django 4.2.16 on 2024-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_alter_tournamentround_competitors_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchup',
            name='status',
            field=models.CharField(choices=[('played', 'played'), ('not played', 'not played')], default='not played', max_length=255),
        ),
    ]
