# Generated by Django 4.2.16 on 2024-12-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_id', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_eng', models.CharField(max_length=100)),
                ('city_ru', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('beauty_ai_rate', models.FloatField(blank=True, null=True)),
                ('image_full_path', models.CharField(max_length=255)),
                ('image_local_path', models.CharField(max_length=255)),
                ('competitor', models.ManyToManyField(related_name='images', to='competitors.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('study', models.CharField(blank=True, max_length=255, null=True)),
                ('home', models.CharField(blank=True, max_length=255, null=True)),
                ('looking_for', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=255, null=True)),
                ('lifestyle', models.TextField(blank=True, max_length=1000, null=True)),
                ('more_about_me', models.TextField(blank=True, max_length=1000, null=True)),
                ('languages', models.TextField(blank=True, max_length=1000, null=True)),
                ('tinder_scrape_time', models.DateTimeField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='competitors.competitor')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor', to='competitors.location'),
        ),
    ]
