# Generated by Django 4.2.16 on 2024-12-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitordetails',
            name='competitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='competitors.competitor'),
        ),
    ]
