services:
  web:
    build:
      context: ..
      dockerfile: _docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - /mnt/g/facemash/images:/app/media
    env_file:
      - ../.env  # Добавляем загрузку .env для Django
    depends_on:
      - db
    command: ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../.env  # Загружаем переменные для PostgreSQL
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
